server:
  port: 2021
spring:
  application:
    name: sob_blog_system
  datasource:
    url: jdbc:mysql://192.168.127.129:3306/sob_blog_system?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  redis:
    port: 6379
    host: 192.168.127.129
    password: 123456
blog.image.save-Path : \user\aviccii\Blog\images
# 2M
blog.image.max-size : 2097152