server:
  port: 2020
spring:
  application:
    name: sob_blog_system
  datasource:
    url: jdbc:mysql://192.168.127.129:3306/sob_blog_system?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
